name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build ./...

      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_HUB_LOGIN}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
      - name: Build docker image
        run: docker build -t alrickaren/go .
      - name: Publish to Docker Hub
        run: docker push arenalrick/go:latest

  deploy:
    needs: build
    runs-on: [ip-172-31-11-187]
    steps:
      - name: Pull image from docker hub
        run: docker pull arenalrick/go:latest
      - name: Delete old container
        run: docker rm -f go-example-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name go-example-container arenalrick/go:latest
